#markdown: rdiscount 
permalink: /:year/:month/:day/:title 
title: Luoliang
url: http://www.luoliang.net
subscribe: http://www.luoliang.net/feed.xml
exclude: [ README.md, newpost.rb ]
domain: luoliang.net
author: Luo Liang
email: llmainland+blog@live.cn
auto: true
twitterID: Luoliang
googleAnalyticsID: UA-5531632-1
disqusShortname: luoliang
